CREATE DATABASE `SHOPEE-MANAGEMENT`;
USE `SHOPEE-MANAGEMENT`;
CREATE TABLE `CATEGORIES`(
`ID` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
`NAME` VARCHAR(50)
);
CREATE TABLE `PRODUCTS`(
`ID` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
`NAME` VARCHAR(50),
`PRICE` BIGINT(20),
`CATEGORY-ID` BIGINT UNSIGNED
);
CREATE TABLE `VARIANTS`(
`ID` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
`COLOR` VARCHAR(50),
`SIZE` VARCHAR(10),
`PRODUCT-ID` BIGINT UNSIGNED
);
CREATE TABLE `USER`(
`ID` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
`NAME` VARCHAR(50),
`AGE` INT(2) UNSIGNED,
`ADDRESS` VARCHAR(50) UNIQUE,
`CART-ID` BIGINT UNSIGNED
);
CREATE TABLE `CART`(
`ID` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
`USER-ID` BIGINT UNSIGNED UNIQUE
);
CREATE TABLE CART_ITEM
(
`ID` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
`CART-ID` BIGINT UNSIGNED,
`VARIANT-ID` BIGINT UNSIGNED,
`PRODUCT-ID` BIGINT UNSIGNED,
`QUANTITY` INT UNSIGNED
);
CREATE TABLE `ORDER`(
`ID` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
`USER-ID` BIGINT UNSIGNED,
`USER_ADDRESS` VARCHAR(50)
);
CREATE TABLE `ORDERD_DETAIL`(
`ID` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
`ORDER-ID` BIGINT UNSIGNED,
CART_ITEM_ID BIGINT UNSIGNED
);

/* Add Foreign key */
ALTER TABLE `PRODUCTS`
ADD FOREIGN KEY(`CATEGORY-ID`) REFERENCES CATEGORIES(`ID`);

ALTER TABLE `VARIANTS`
ADD FOREIGN KEY(`PRODUCT-ID`) REFERENCES PRODUCTS(`ID`);

ALTER TABLE CART_ITEM
ADD FOREIGN KEY(`VARIANT-ID`) REFERENCES VARIANTS(`ID`);

ALTER TABLE CART_ITEM
ADD FOREIGN KEY(`PRODUCT-ID`) REFERENCES PRODUCTS(`ID`);

ALTER TABLE CART_ITEM
ADD FOREIGN KEY(`CART-ID`) REFERENCES CART(`ID`);

ALTER TABLE `CART`
ADD FOREIGN KEY(`USER-ID`) REFERENCES `USER`(`ID`);

ALTER TABLE `USER`
ADD FOREIGN KEY(`CART-ID`) REFERENCES CART(`ID`);

ALTER TABLE `ORDER`
ADD FOREIGN KEY(`USER-ID`) REFERENCES `USER`(`ID`);

ALTER TABLE `ORDER`
ADD FOREIGN KEY (USER_ADDRESS) REFERENCES USER(ADDRESS);

ALTER TABLE `ORDERD_DETAIL`
ADD FOREIGN KEY(`ORDER-ID`) REFERENCES `ORDER`(`ID`);

ALTER TABLE `ORDERD_DETAIL`
ADD FOREIGN KEY (CART_ITEM_ID) REFERENCES CART_ITEM(ID);

/* Add Data */
INSERT INTO `CATEGORIES` (`NAME`)
VALUES ('Technology Device'),
       ('Laptop'),
       ('Men Fashion'),
       ('Women Fashion'),
       ('Watch');

# SELECT * FROM CATEGORIES

INSERT INTO PRODUCTS (`NAME`, PRICE, `CATEGORY-ID`)
VALUES ('Headphone','100000',1),
       ('Loud speaker','200000',1),
       ('Loud speaker bluetooth','200000',1),
       ('Micro','150000',1),
       ('Lamp','50000',1),

       ('Laptop ASUS','50000000',2),
       ('Laptop DELL','25000000',2),
       ('Laptop MSI','27000000',2),
       ('Laptop ACER','40000000',2),
       ('MACBOOK','100000000',2),

       ('Hoddie','400000',3),
       ('T-shirt','350000',3),
       ('Jeans','500000',3),
       ('Shirt','450000',3),
       ('Socks','50000',3),

       ('Dress','500000',4),
       ('Jacket','250000',4),
       ('Sweater','300000',4),
       ('Skirt','450000',4),
       ('Cardigan','200000',4),

       ('Apple watch','6000000',5),
       ('Pilot watch','8000000',5),
       ('Sport watch','2000000',5),
       ('Mechanical watch','2500000000',5),
       ('Bussiness','100000',5);

# SELECT * FROM PRODUCTS;

INSERT INTO VARIANTS (COLOR, SIZE, `PRODUCT-ID`)
VALUES ('Black','13 INCH',6),
        ('Black','14 INCH',6),
        ('Red','15 INCH',6),
        ('White','16 INCH',6),

        ('Black','L',11),
        ('Black','XL',11),
        ('White','XXL',11),
        ('Green','XXL',11);

# SELECT * FROM VARIANTS

INSERT INTO USER (`NAME`, AGE, ADDRESS, `CART-ID`)
VALUES ('USER 1', 18, 'DISTRIC 1', 1),
       ('USER 2', 19, 'DISTRIC 2', 2),
       ('USER 3', 20, 'DISTRIC 3', 3),
       ('USER 4', 21, 'DISTRIC 4', 4),
       ('USER 5', 22, 'DISTRIC 5', 5);

# SELECT * FROM USER

INSERT INTO CART (`USER-ID`)
VALUES (1),
       (2),
       (3),
       (4),
       (5);

# SELECT * FROM CART;

#2. SHOW ALL CATEGORIES
SELECT * FROM CATEGORIES;

# 3. SHOW ALL PRODUCT (CATEGORY ID = 1)
SELECT * FROM PRODUCTS
WHERE `CATEGORY-ID` = 1;

# 4. SHOW ALL PRODUCT DETAIL
SELECT `CATEGORIES`.NAME AS CATEGORIES, PRODUCTS.NAME AS PRODUCT, PRODUCTS.PRICE AS PRICE, VARIANTS.COLOR AS COLOR, VARIANTS.SIZE AS SIZE
FROM PRODUCTS
INNER JOIN VARIANTS ON PRODUCTS.ID = VARIANTS.`PRODUCT-ID`
INNER JOIN CATEGORIES ON CATEGORIES.ID = PRODUCTS.`CATEGORY-ID`;

#5. CREATE CARTLINE
DELIMITER //
CREATE PROCEDURE CREATE_CART_ITEM(IN PRODUCT_ID BIGINT UNSIGNED, IN VARIANT_ID BIGINT UNSIGNED, IN CART_ID BIGINT UNSIGNED, QUANTITY_NUMBER INT)
BEGIN
   INSERT INTO `CART_ITEM` (`CART-ID`, `VARIANT-ID`, `PRODUCT-ID`, QUANTITY)
       VALUE (`CART_ID`, `VARIANT_ID`, `PRODUCT_ID`, `QUANTITY_NUMBER`);
END //
DELIMITER ;

CALL CREATE_CART_ITEM(6,1,1,10);
CALL CREATE_CART_ITEM(6,2,2,100);
CALL CREATE_CART_ITEM(6,3,3,2000);
CALL CREATE_CART_ITEM(6,4,4,1569);

CALL CREATE_CART_ITEM(11,5,5,2000);
CALL CREATE_CART_ITEM(11,6,5,10000);
CALL CREATE_CART_ITEM(11,7,5,12456);
CALL CREATE_CART_ITEM(11,8,5,500000);

# SELECT * FROM CART_ITEM
# SELECT * FROM view_variantID_and_productID;

# 6. Show all cart + cart item
SELECT CART.ID AS `CART_ID`, PRODUCTS.NAME AS `PRODUCT_NAME`,                VARIANTS.COLOR AS COLOR, VARIANTS.SIZE, PRODUCTS.PRICE AS PRICE, CART_ITEM.QUANTITY, CART_ITEM.QUANTITY * PRODUCTS.PRICE AS SUB_TOTAL_PRICE
    FROM CART_ITEM
LEFT JOIN CART ON CART_ITEM.`CART-ID` = CART.ID
LEFT JOIN PRODUCTS ON CART_ITEM.`PRODUCT-ID` = PRODUCTS.ID
LEFT JOIN VARIANTS ON CART_ITEM.`VARIANT-ID` = VARIANTS.ID;

# 7. UPDATE QUANTITY OF CART_ITEM
UPDATE CART_ITEM
SET QUANTITY = 1024 WHERE ID = 1;

#8.1 CREATE ORDER FROM CART AND ADDRESS
DELIMITER //
CREATE PROCEDURE CREATE_ORDER(IN ID_USER BIGINT UNSIGNED, IN ADDRESS BIGINT UNSIGNED)
BEGIN
   INSERT INTO `ORDER`(`USER-ID`, USER_ADDRESS)
       VALUE (ID_USER,ADDRESS);
END //
DELIMITER ;

SELECT * FROM CART_ITEM;
SELECT `VARIANT-ID` FROM  CART_ITEM
WHERE CART_ITEM.`PRODUCT-ID` = 6;

SELECT * FROM PRODUCTS WHERE `NAME` LIKE '%a%';

ALTER TABLE `ORDER`
DROP FOREIGN KEY order_ibfk_2

